# Numpy

We have seen python basic data structures in our last section. They are great but lack specialized features for data analysis. Like, adding rows, columns, operating on 2d matrices aren't readily available. So, we will use *numpy* for such functions.



In [41]:
import numpy as np

Numpy operates on *nd* arrays. These are similar to lists but contains homogenous elements but easier to store 2-d data.

In [42]:
l1 = [1,2,3,4]
nd1 = np.array(l1)
print(nd1)

l2 = [5,6,7,8]
nd2 = np.array([l1,l2])
print(nd2)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


Sum functions on np.array()

In [43]:
print(nd2.shape)

print(nd2.size)

print(nd2.dtype)

(2, 4)
8
int64


### Question 1

Create an identity 2d-array or matrix (with ones across the diagonal).

[ **Hint:** You can also use **np.identity()** function ]

In [44]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

### Question 2

Create a 2d-array or matrix of order 3x3 with values = 9,8,7,6,5,4,3,2,1 arranged in the same order.

Use: **np.array()** function



In [73]:
so_list = [[9,8,7],[6,5,4],[3,2,1]]
my_j = np.array(so_list)
print(my_j)


[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [45]:
my_array = np.array([[9,8,7],[6,5,4],[3,2,1]])
my_array

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [46]:
the_array = np.array([[6,8,9], [5,8,3],[4,5,2]])
print(the_array)

[[6 8 9]
 [5 8 3]
 [4 5 2]]


### Question 3

Interchange both the rows and columns of the given matrix.

Hint: You can use the transpose **.T**)

In [14]:
my_array.T

array([[9, 6, 3],
       [8, 5, 2],
       [7, 4, 1]])

In [18]:
the_array.T

array([[6, 5, 4],
       [8, 8, 5],
       [9, 3, 2]])

### Question 4
Add + 1 to all the elements in the given matrix.

In [25]:
my_array.T + 1

array([[10,  7,  4],
       [ 9,  6,  3],
       [ 8,  5,  2]])

In [24]:
the_array + 2

array([[ 8, 10, 11],
       [ 7, 10,  5],
       [ 6,  7,  4]])

In [26]:
the_array.T + 2

array([[ 8,  7,  6],
       [10, 10,  7],
       [11,  5,  4]])

Similarly you can do operations like scalar  substraction, division, multiplication (operating on each element in the matrix)

### Question 5

Find the mean of all elements in the given matrix nd6.
nd6 = [[  1   4   9 121 144 169]
 [ 16  25  36 196 225 256]
 [ 49  64  81 289 324 361]]
 
 Use: **.mean()** function


In [36]:
nd6 = [[1, 4, 9, 121, 144, 169], [16, 25, 36, 196, 225, 256], [49, 64, 81, 289, 324, 361]]
my_ray = np.matrix(nd6)
my_ray

matrix([[  1,   4,   9, 121, 144, 169],
        [ 16,  25,  36, 196, 225, 256],
        [ 49,  64,  81, 289, 324, 361]])

In [35]:
my_ray.mean()

131.66666666666666

### Question 7

Find the dot product of two given matrices.

[**Hint:** Use **np.dot()**]

In [47]:
np.dot(my_array ,my_ray)

matrix([[ 480,  684,  936, 4680, 5364, 6096],
        [ 282,  405,  558, 2862, 3285, 3738],
        [  84,  126,  180, 1044, 1206, 1380]])

### Array Slicing/Indexing:

- Now we'll learn to access multiple elements or a range of elements from an array.

In [48]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### Question 8

Print the array elements from start to 4th position


In [53]:
x[:5] #to the 4th position


array([0, 1, 2, 3, 4])

In [54]:
x[1:5] #from index 1 to the 4th postion

array([1, 2, 3, 4])

In [55]:
x[5:15] #from index 5 to the 14th postion

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
 x[:13] # to the 12th postion

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Question 9

- Return elements from first position with step size 2. (Difference between consecutive elements is 2)

In [65]:
x[1::2]  # Returns the elements of array 
          #from 2nd element to further elements with step size of 2.

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

### Question 10

Reverse the array using array indexing:

In [71]:
x[::-1] 

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])